import {
  bigint,
  boolean,
  date,
  index,
  jsonb,
  numeric,
  pgTable,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

export const campaigns = pgTable("campaigns", {
  _airbyteRawId: varchar("_airbyte_raw_id").primaryKey(),
  _airbyteExtractedAt: timestamp("_airbyte_extracted_at", {
    withTimezone: true,
  }).notNull(),
  _airbyteMeta: jsonb("_airbyte_meta").notNull(),
  _airbyteGenerationId: bigint("_airbyte_generation_id", {
    mode: "number",
  }).notNull(),
  id: varchar("id"),
  name: varchar("name"),
  status: varchar("status"),
  adlabels: jsonb("adlabels"),
  objective: varchar("objective"),
  spendCap: numeric("spend_cap"),
  stopTime: timestamp("stop_time", { withTimezone: true }),
  accountId: varchar("account_id"),
  startTime: timestamp("start_time", { withTimezone: true }),
  buyingType: varchar("buying_type"),
  issuesInfo: jsonb("issues_info"),
  bidStrategy: varchar("bid_strategy"),
  createdTime: timestamp("created_time", { withTimezone: true }),
  dailyBudget: numeric("daily_budget"),
  updatedTime: timestamp("updated_time", { withTimezone: true }),
  lifetimeBudget: numeric("lifetime_budget"),
  budgetRemaining: numeric("budget_remaining"),
  effectiveStatus: varchar("effective_status"),
  boostedObjectId: varchar("boosted_object_id"),
  configuredStatus: varchar("configured_status"),
  sourceCampaignId: numeric("source_campaign_id"),
  specialAdCategory: varchar("special_ad_category"),
  smartPromotionType: varchar("smart_promotion_type"),
  budgetRebalanceFlag: boolean("budget_rebalance_flag"),
  specialAdCategoryCountry: jsonb("special_ad_category_country"),
});

export const adSets = pgTable("ad_sets", {
  _airbyteRawId: varchar("_airbyte_raw_id").primaryKey(),
  _airbyteExtractedAt: timestamp("_airbyte_extracted_at", {
    withTimezone: true,
  }).notNull(),
  _airbyteMeta: jsonb("_airbyte_meta").notNull(),
  _airbyteGenerationId: bigint("_airbyte_generation_id", {
    mode: "number",
  }).notNull(),
  id: varchar("id"),
  name: varchar("name"),
  adlabels: jsonb("adlabels"),
  bidInfo: jsonb("bid_info"),
  endTime: timestamp("end_time", { withTimezone: true }),
  targeting: jsonb("targeting"),
  accountId: varchar("account_id"),
  bidAmount: numeric("bid_amount"),
  startTime: timestamp("start_time", { withTimezone: true }),
  campaignId: varchar("campaign_id"),
  bidStrategy: varchar("bid_strategy"),
  createdTime: timestamp("created_time", { withTimezone: true }),
  dailyBudget: numeric("daily_budget"),
  updatedTime: timestamp("updated_time", { withTimezone: true }),
  bidConstraints: jsonb("bid_constraints"),
  lifetimeBudget: numeric("lifetime_budget"),
  promotedObject: jsonb("promoted_object"),
  budgetRemaining: numeric("budget_remaining"),
  effectiveStatus: varchar("effective_status"),
  learningStagInfo: jsonb("learning_stage_info"),
});

export const ads = pgTable("ads", {
  _airbyteRawId: varchar("_airbyte_raw_id").primaryKey(),
  _airbyteExtractedAt: timestamp("_airbyte_extracted_at", {
    withTimezone: true,
  }).notNull(),
  _airbyteMeta: jsonb("_airbyte_meta").notNull(),
  _airbyteGenerationId: bigint("_airbyte_generation_id", {
    mode: "number",
  }).notNull(),
  id: varchar("id"),
  name: varchar("name"),
  status: varchar("status"),
  adlabels: jsonb("adlabels"),
  adsetId: varchar("adset_id"),
  bidInfo: jsonb("bid_info"),
  bidType: varchar("bid_type"),
  creative: jsonb("creative"),
  targeting: jsonb("targeting"),
  accountId: varchar("account_id"),
  bidAmount: bigint("bid_amount", { mode: "number" }),
  campaignId: varchar("campaign_id"),
  createdTime: timestamp("created_time", { withTimezone: true }),
  sourceAdId: varchar("source_ad_id"),
  updatedTime: timestamp("updated_time", { withTimezone: true }),
  trackingSpecs: jsonb("tracking_specs"),
  recommendations: jsonb("recommendations"),
  conversionSpecs: jsonb("conversion_specs"),
  effectiveStatus: varchar("effective_status"),
  lastUpdatedByAppId: varchar("last_updated_by_app_id"),
});

export const adsInsights = pgTable(
  "ads_insights",
  {
    _airbyteRawId: varchar("_airbyte_raw_id").primaryKey(),
    _airbyteExtractedAt: timestamp("_airbyte_extracted_at", {
      withTimezone: true,
    }).notNull(),
    _airbyteMeta: jsonb("_airbyte_meta").notNull(),
    _airbyteGenerationId: bigint("_airbyte_generation_id", {
      mode: "number",
    }).notNull(),
    cpc: numeric("cpc"),
    cpm: numeric("cpm"),
    cpp: numeric("cpp"),
    ctr: numeric("ctr"),
    adId: varchar("ad_id"),
    reach: bigint("reach", { mode: "number" }),
    spend: numeric("spend"),
    clicks: bigint("clicks", { mode: "number" }),
    actions: jsonb("actions").$type<
      { action_type: string; value: number | string }[]
    >(),
    adName: varchar("ad_name"),
    adsetId: varchar("adset_id"),
    dateStop: date("date_stop"),
    frequency: numeric("frequency"),
    objective: varchar("objective"),
    accountId: varchar("account_id"),
    adsetName: varchar("adset_name"),
    dateStart: date("date_start"),
    uniqueCtr: numeric("unique_ctr"),
    auctionBid: numeric("auction_bid"),
    buyingType: varchar("buying_type"),
    campaignId: varchar("campaign_id"),
    conversions: jsonb("conversions"),
    impressions: bigint("impressions", { mode: "number" }),
    websiteCtr: jsonb("website_ctr"),
    accountName: varchar("account_name"),
    createdTime: date("created_time"),
    updatedTime: date("updated_time"),
    socialSpend: numeric("social_spend"),
    actionValues: jsonb("action_values"),
    campaignName: varchar("campaign_name"),
    purchaseRoas: jsonb("purchase_roas"),
    uniqueClicks: bigint("unique_clicks", { mode: "number" }),
    uniqueActions: jsonb("unique_actions"),
    fullViewReach: numeric("full_view_reach"),
    outboundClicks: jsonb("outbound_clicks"),
    qualityRanking: varchar("quality_ranking"),
    accountCurrency: varchar("account_currency"),
    adClickActions: jsonb("ad_click_actions"),
    conversionValues: jsonb("conversion_values"),
    costPerAdClick: jsonb("cost_per_ad_click"),
    costPerThruplay: jsonb("cost_per_thruplay"),
    optimizationGoal: varchar("optimization_goal"),
    inlineLinkClicks: bigint("inline_link_clicks", { mode: "number" }),
    videoPlayActions: jsonb("video_play_actions"),
    attributionSetting: varchar("attribution_setting"),
    costPerConversion: jsonb("cost_per_conversion"),
    outboundClicksCtr: jsonb("outbound_clicks_ctr"),
    canvasAvgViewTime: numeric("canvas_avg_view_time"),
    costPerActionType: jsonb("cost_per_action_type"),
    adImpressionActions: jsonb("ad_impression_actions"),
    catalogSegmentValue: jsonb("catalog_segment_value"),
    costPerUniqueClick: numeric("cost_per_unique_click"),
    fullViewImpressions: numeric("full_view_impressions"),
    inlineLinkClickCtr: numeric("inline_link_click_ctr"),
    websitePurchaseRoas: jsonb("website_purchase_roas"),
    estimatedAdRecallers: numeric("estimated_ad_recallers"),
    inlinePostEngagement: bigint("inline_post_engagement", {
      mode: "number",
    }),
    uniqueLinkClicksCtr: numeric("unique_link_clicks_ctr"),
    uniqueOutboundClicks: jsonb("unique_outbound_clicks"),
    auctionCompetitiveness: numeric("auction_competitiveness"),
    canvasAvgViewPercent: numeric("canvas_avg_view_percent"),
    catalogSegmentActions: jsonb("catalog_segment_actions"),
    conversionRateRanking: varchar("conversion_rate_ranking"),
    convertedProductValue: jsonb("converted_product_value"),
    costPerOutboundClick: jsonb("cost_per_outbound_click"),
    engagementRateRanking: varchar("engagement_rate_ranking"),
    mobileAppPurchaseRoas: jsonb("mobile_app_purchase_roas"),
    videoPlayCurveActions: jsonb("video_play_curve_actions"),
    uniqueInlineLinkClicks: bigint("unique_inline_link_clicks", {
      mode: "number",
    }),
    videoP25WatchedActions: jsonb("video_p25_watched_actions"),
    videoP50WatchedActions: jsonb("video_p50_watched_actions"),
    videoP75WatchedActions: jsonb("video_p75_watched_actions"),
    videoP95WatchedActions: jsonb("video_p95_watched_actions"),
    auctionMaxCompetitorBid: numeric("auction_max_competitor_bid"),
    convertedProductQuantity: jsonb("converted_product_quantity"),
    costPer15SecVideoView: jsonb("cost_per_15_sec_video_view"),
    costPerInlineLinkClick: numeric("cost_per_inline_link_click"),
    uniqueOutboundClicksCtr: jsonb("unique_outbound_clicks_ctr"),
    videoP100WatchedActions: jsonb("video_p100_watched_actions"),
    videoTimeWatchedActions: jsonb("video_time_watched_actions"),
    costPerUniqueActionType: jsonb("cost_per_unique_action_type"),
    uniqueInlineLinkClickCtr: numeric("unique_inline_link_click_ctr"),
    video15SecWatchedActions: jsonb("video_15_sec_watched_actions"),
    video30SecWatchedActions: jsonb("video_30_sec_watched_actions"),
    costPerUniqueOutboundClick: jsonb("cost_per_unique_outbound_click"),
    videoAvgTimeWatchedActions: jsonb("video_avg_time_watched_actions"),
    costPerEstimatedAdRecallers: numeric(
      "cost_per_estimated_ad_recallers",
    ),
    costPerInlinePostEngagement: numeric(
      "cost_per_inline_post_engagement",
    ),
    costPerUniqueInlineLinkClick: numeric(
      "cost_per_unique_inline_link_click",
    ),
    instantExperienceClicksToOpen: numeric(
      "instant_experience_clicks_to_open",
    ),
    instantExperienceClicksToStart: numeric(
      "instant_experience_clicks_to_start",
    ),
    instantExperienceOutboundClicks: jsonb(
      "instant_experience_outbound_clicks",
    ),
    videoPlayRetentionGraphActions: jsonb(
      "video_play_retention_graph_actions",
    ),
    costPer2SecContinuousVideoView: jsonb(
      "cost_per_2_sec_continuous_video_view",
    ),
    videoPlayRetention0To15sActions: jsonb(
      "video_play_retention_0_to_15s_actions",
    ),
    videoContinuous2SecWatchedActions: jsonb(
      "video_continuous_2_sec_watched_actions",
    ),
    videoPlayRetention20To60sActions: jsonb(
      "video_play_retention_20_to_60s_actions",
    ),
    qualifyingQuestionQualifyAnswerRate: numeric(
      "qualifying_question_qualify_answer_rate",
    ),
    catalogSegmentValueOmniPurchaseRoas: jsonb(
      "catalog_segment_value_omni_purchase_roas",
    ),
    catalogSegmentValueMobilePurchaseRoas: jsonb(
      "catalog_segment_value_mobile_purchase_roas",
    ),
    catalogSegmentValueWebsitePurchaseRoas: jsonb(
      "catalog_segment_value_website_purchase_roas",
    ),
  },
  (table) => [
    index("idx_ads_insights_date_start").on(table.dateStart),
    index("idx_ads_insights_campaign_id").on(table.campaignId),
    index("idx_ads_insights_campaign_date").on(
      table.campaignId,
      table.dateStart,
    ),
  ],
);
